print("This file was created within RStudio")
print("and it now lives on GitHub")
print("This is more of a test")
print("I am now uploading this from my mac")
print("Trying to commit with RSA on my mac")